#!/usr/bin/env python3
"""Drop-soundness fuzzer (Bet 4 follow-up).

The HIR engine has no node for an implicit, scope-exit `Drop`, so an effectful `Drop` guard (I/O on
the way out — an RAII transaction/lock/flush) was invisible to it. The fix reads MIR `Drop` terminators
and follows the dropped type's reachable LOCAL `Drop::drop` impls — directly, through value-embedded
fields (struct/tuple/array/enum), AND through std OWNING containers (Box/Vec/Rc/Arc/HashMap/…), whose
element is hidden behind a heap pointer. This generator makes that a tested gate: it threads a KNOWN
effect into a `Guard`'s `Drop`, wraps the guard in a random container FORM, lets it drop, and asserts
the dropping function inherits the effect (or `Unknown`). A function reported PURE is a silent
under-report — the same trust-contract violation the rest of the harness hunts, but via drop glue.

Usage:  gen_drop.py <seed> <out-dir>     # writes <out-dir>/{Cargo.toml, src/main.rs, truth.json}
"""
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen import effects_for  # noqa: E402

# Each form wraps a `Guard` value in a type that, when dropped, must still run `Guard::drop` — directly,
# through a value field, or through a std owning container's heap-indirected drop glue.
DROP_FORMS = {
    "direct": "Guard",
    "field":  "S { g: Guard }",                 # value field of a local struct
    "tuple":  "(0u8, Guard)",
    "array":  "[Guard]",
    "option": "Some(Guard)",                    # enum variant
    "box":    "Box::new(Guard)",                # heap, single
    "vec":    "vec![Guard]",                    # heap, collection
    "rc":     "std::rc::Rc::new(Guard)",        # refcounted (drops on last ref — over-approximate)
    "arc":    "std::sync::Arc::new(Guard)",
    "hashmap": "{ let mut m = std::collections::HashMap::new(); m.insert(0u8, Guard); m }",
    "nested": "vec![Box::new(Guard)]",          # container-of-container
    # a CLOSURE that captured the guard by move, dropped WITHOUT ever being called. Closures are their
    # own `TyKind` (not `TyKind::Adt`), so the field/element walker needs a dedicated arm for them — a
    # real hole found 2026-08-29 (a captured effectful Drop was silently lost on scope-exit-only drop).
    "closure": "{ let g = Guard; move || { let _ = &g; } }",
}


def main():
    seed = int(sys.argv[1])
    out = sys.argv[2]
    rng = random.Random(seed)

    EFFECTS = effects_for(seed)
    allowed = os.environ.get("CANDOR_FUZZ_EFFECTS", "").split() or list(EFFECTS)
    effect = rng.choice([e for e in EFFECTS if e in allowed])
    leaf, marker = EFFECTS[effect]
    n = rng.randint(3, 9)

    fns = [f"f{i:02d}" for i in range(n)]
    forms_log = {}
    bodies = {}
    for name in fns:
        form = rng.choice(list(DROP_FORMS))
        forms_log[name] = form
        bodies[name] = "let _x = %s;" % DROP_FORMS[form]

    lines = [
        "// GENERATED by soundness/gen_drop.py — do not edit. seed=%d effect=%s" % (seed, effect),
        "struct Guard;",
        "impl Drop for Guard { fn drop(&mut self) { %s } }" % leaf,
        "struct S { g: Guard }",
        "",
    ]
    for name in fns:
        lines.append("fn %s() { %s }" % (name, bodies[name]))
    lines.append("")
    lines.append("fn main() { %s }" % " ".join("%s();" % f for f in fns))

    expected = set(fns) | {"main"}
    os.makedirs(os.path.join(out, "src"), exist_ok=True)
    with open(os.path.join(out, "Cargo.toml"), "w") as f:
        f.write('[package]\nname = "candor_drop"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n')
    with open(os.path.join(out, "src", "main.rs"), "w") as f:
        f.write("\n".join(lines) + "\n")
    with open(os.path.join(out, "truth.json"), "w") as f:
        json.dump(
            {"seed": seed, "effect": effect, "marker": marker, "expect": sorted(expected), "forms": forms_log},
            f, indent=2,
        )


if __name__ == "__main__":
    main()
