#!/usr/bin/env python3
"""Cross-crate soundness fuzzer (extends the harness to the crate boundary).

The single-crate fuzzer can't reach candor's CROSS-crate machinery (DefPathHash linking + version
trust), which is its own hard, bug-prone surface. This generator emits ONE package compiled as both a
lib and a bin (the dylint-friendly way to get two linted crates that reference each other): the LIB
performs a known effect in `dep_sink`; the BIN chains `f00 -> ... -> xc::dep_entry()` where the final
edge CROSSES the crate boundary, and each edge uses a random call form. The bin must inherit the lib's
effect across the boundary — directly (precise) or as `Unknown` (sound). A bin/lib function that
reaches the effect but is reported PURE (or omitted) is a silent cross-crate under-report.

Usage:  gen_cross.py <seed> <out-dir>
"""
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen import CONSTRUCTION_ONLY, HELPERS, edge_forms, effects_for  # noqa: E402


def main():
    seed = int(sys.argv[1])
    out = sys.argv[2]
    rng = random.Random(seed)

    EFFECTS = effects_for(seed)
    allowed = os.environ.get("CANDOR_FUZZ_EFFECTS", "").split() or list(EFFECTS)
    effect = rng.choice([e for e in EFFECTS if e in allowed])
    leaf, marker = EFFECTS[effect]
    n = rng.randint(2, 7)  # bin chain length

    binfns = [f"f{i:02d}" for i in range(n)]
    bodies = {}
    needed = set()
    extra_items = []  # per-edge module-level items (operator-overload structs/impls)
    expected = set(binfns) | {"main", "dep_sink", "dep_entry"}
    forms_log = {}

    # Sometimes make the boundary edge dispatch through a NON-LOCAL trait object with an arbitrary self
    # type: `Arc<dyn xc::LibJob>` where `LibJob::run(self: Arc<Self>)` is defined in the lib. From the
    # bin, `LibJob` is non-local, so CHA can't enumerate its impls — the *only* sound answer for the
    # invoking `recv_arc` is `Unknown`. This is the is_dyn_receiver (#4) path WITH TEETH: peel_refs
    # alone leaves `dynamic = false`, no CHA, and (#4-bug) no `Unknown` → a silent under-report.
    use_arc = rng.random() < 0.45

    for i in range(n):
        last = i + 1 == n
        if last and use_arc:
            bodies[binfns[i]] = "recv_arc(xc::make_job());"
            needed.add("recv_arc")
            expected.add("recv_arc")
            forms_log[binfns[i]] = "CROSS:arc_nonlocal"
            continue
        # the LAST bin edge crosses into the lib (xc::dep_entry); earlier edges are intra-bin.
        callee = binfns[i + 1] if not last else "xc::dep_entry"
        forms = edge_forms(callee, i)
        form = rng.choice([f for f in forms if f not in CONSTRUCTION_ONLY])
        body, helpers, extra, items = forms[form]
        bodies[binfns[i]] = body
        needed.update(helpers)
        expected.update(extra)
        extra_items.extend(items)
        forms_log[binfns[i]] = ("CROSS:" + form) if last else form

    # ---- lib.rs: the dependency performing the effect ----
    lib = [
        "// GENERATED by soundness/gen_cross.py — do not edit. seed=%d effect=%s" % (seed, effect),
        "pub fn dep_sink() { %s }" % leaf,
        "pub fn dep_entry() { dep_sink(); }",
    ]
    if use_arc:
        # a lib-defined trait object with an arbitrary self type, performing the effect in its impl.
        # Fully-qualified `std::sync::Arc` (no `use`) so it never clashes with the arc_run helper's import.
        lib += [
            "pub trait LibJob { fn run(self: std::sync::Arc<Self>); }",
            "pub struct LibImpl;",
            "impl LibJob for LibImpl { fn run(self: std::sync::Arc<Self>) { dep_sink(); } }",
            "pub fn make_job() -> std::sync::Arc<dyn LibJob> { std::sync::Arc::new(LibImpl) }",
        ]
        expected.add("run")  # the lib impl's `run` reaches the effect via dep_sink
    lib.append("")

    # ---- main.rs: the bin chaining across the boundary ----
    bin_ = ["// GENERATED. seed=%d effect=%s (cross-crate)" % (seed, effect), ""]
    if use_arc:
        bin_.append("fn recv_arc(j: std::sync::Arc<dyn xc::LibJob>) { j.run(); }")
    for h in HELPERS:
        if h in needed:
            bin_.append(HELPERS[h])
    for item in extra_items:  # per-edge operator-overload structs + effectful trait impls
        bin_.append(item)
    bin_.append("")
    for name in binfns:
        bin_.append("fn %s() { %s }" % (name, bodies[name]))
    bin_.append("")
    bin_.append("fn main() { %s(); }" % binfns[0])

    os.makedirs(os.path.join(out, "src"), exist_ok=True)
    with open(os.path.join(out, "Cargo.toml"), "w") as f:
        f.write('[package]\nname = "xc"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n')
    with open(os.path.join(out, "src", "lib.rs"), "w") as f:
        f.write("\n".join(lib) + "\n")
    with open(os.path.join(out, "src", "main.rs"), "w") as f:
        f.write("\n".join(bin_) + "\n")
    with open(os.path.join(out, "truth.json"), "w") as f:
        json.dump(
            {"seed": seed, "effect": effect, "marker": marker, "expect": sorted(expected),
             "forms": forms_log, "cross": True},
            f, indent=2,
        )


if __name__ == "__main__":
    main()
