#!/usr/bin/env python3
"""Cross-crate soundness fuzzer (extends the harness to the crate boundary).

The single-crate fuzzer can't reach candor's CROSS-crate machinery (DefPathHash linking + version
trust), which is its own hard, bug-prone surface. This generator emits ONE package compiled as both a
lib and a bin (the dylint-friendly way to get two linted crates that reference each other): the LIB
performs a known effect in `dep_sink`; the BIN chains `f00 -> ... -> xc::dep_entry()` where the final
edge CROSSES the crate boundary, and each edge uses a random call form. The bin must inherit the lib's
effect across the boundary — directly (precise) or as `Unknown` (sound). A bin/lib function that
reaches the effect but is reported PURE (or omitted) is a silent cross-crate under-report.

Usage:  gen_cross.py <seed> <out-dir>
"""
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen import HELPERS, edge_forms, effects_for  # noqa: E402


def main():
    seed = int(sys.argv[1])
    out = sys.argv[2]
    rng = random.Random(seed)

    EFFECTS = effects_for(seed)
    allowed = os.environ.get("CANDOR_FUZZ_EFFECTS", "").split() or list(EFFECTS)
    effect = rng.choice([e for e in EFFECTS if e in allowed])
    leaf, marker = EFFECTS[effect]
    n = rng.randint(2, 7)  # bin chain length

    binfns = [f"f{i:02d}" for i in range(n)]
    bodies = {}
    needed = set()
    expected = set(binfns) | {"main", "dep_sink", "dep_entry"}
    forms_log = {}

    for i in range(n):
        # the LAST bin edge crosses into the lib (xc::dep_entry); earlier edges are intra-bin.
        callee = binfns[i + 1] if i + 1 < n else "xc::dep_entry"
        form = rng.choice(list(edge_forms(callee)))
        body, helpers, extra = edge_forms(callee)[form]
        bodies[binfns[i]] = body
        needed.update(helpers)
        expected.update(extra)
        forms_log[binfns[i]] = ("CROSS:" + form) if i + 1 == n else form

    # ---- lib.rs: the dependency performing the effect ----
    lib = [
        "// GENERATED by soundness/gen_cross.py — do not edit. seed=%d effect=%s" % (seed, effect),
        "pub fn dep_sink() { %s }" % leaf,
        "pub fn dep_entry() { dep_sink(); }",
        "",
    ]

    # ---- main.rs: the bin chaining across the boundary ----
    bin_ = ["// GENERATED. seed=%d effect=%s (cross-crate)" % (seed, effect), ""]
    for h in HELPERS:
        if h in needed:
            bin_.append(HELPERS[h])
    bin_.append("")
    for name in binfns:
        bin_.append("fn %s() { %s }" % (name, bodies[name]))
    bin_.append("")
    bin_.append("fn main() { %s(); }" % binfns[0])

    os.makedirs(os.path.join(out, "src"), exist_ok=True)
    with open(os.path.join(out, "Cargo.toml"), "w") as f:
        f.write('[package]\nname = "xc"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n')
    with open(os.path.join(out, "src", "lib.rs"), "w") as f:
        f.write("\n".join(lib) + "\n")
    with open(os.path.join(out, "src", "main.rs"), "w") as f:
        f.write("\n".join(bin_) + "\n")
    with open(os.path.join(out, "truth.json"), "w") as f:
        json.dump(
            {"seed": seed, "effect": effect, "marker": marker, "expect": sorted(expected),
             "forms": forms_log, "cross": True},
            f, indent=2,
        )


if __name__ == "__main__":
    main()
